import { ISquareState } from "../../models/square";

export const initialBoardState: ISquareState[][] = [
  [
    { selected: false, threatID: null, type: 'light', id: 'a8', x: 0, y: 0, pieceID: 'rd1' },
    { selected: false, threatID: null, type: 'dark',  id: 'b8', x: 0, y: 1, pieceID: 'nd1' },
    { selected: false, threatID: null, type: 'light', id: 'c8', x: 0, y: 2, pieceID: 'bd1' },
    { selected: false, threatID: null, type: 'dark',  id: 'd8', x: 0, y: 3, pieceID: 'qd' },
    { selected: false, threatID: null, type: 'light', id: 'e8', x: 0, y: 4, pieceID: 'kd' },
    { selected: false, threatID: null, type: 'dark',  id: 'f8', x: 0, y: 5, pieceID: 'bd2' },
    { selected: false, threatID: null, type: 'light', id: 'g8', x: 0, y: 6, pieceID: 'nd2' },
    { selected: false, threatID: null, type: 'dark',  id: 'h8', x: 0, y: 7, pieceID: 'rd2' },
  ],
  [
    { selected: false, threatID: null, type: 'dark',  id: 'a7', x: 1, y: 0, pieceID: 'pd1' },
    { selected: false, threatID: null, type: 'light', id: 'b7', x: 1, y: 1, pieceID: 'pd2' },
    { selected: false, threatID: null, type: 'dark',  id: 'c7', x: 1, y: 2, pieceID: 'pd3' },
    { selected: false, threatID: null, type: 'light', id: 'd7', x: 1, y: 3, pieceID: 'pd4' },
    { selected: false, threatID: null, type: 'dark',  id: 'e7', x: 1, y: 4, pieceID: 'pd5' },
    { selected: false, threatID: null, type: 'light', id: 'f7', x: 1, y: 5, pieceID: 'pd6' },
    { selected: false, threatID: null, type: 'dark',  id: 'g7', x: 1, y: 6, pieceID: 'pd7' },
    { selected: false, threatID: null, type: 'light', id: 'h7', x: 1, y: 7, pieceID: 'pd8' },
  ],
  [
    { selected: false, threatID: null, type: 'light', id: 'a6', x: 2, y: 0, pieceID: null },
    { selected: false, threatID: null, type: 'dark',  id: 'b6', x: 2, y: 1, pieceID: null },
    { selected: false, threatID: null, type: 'light', id: 'c6', x: 2, y: 2, pieceID: null },
    { selected: false, threatID: null, type: 'dark',  id: 'd6', x: 2, y: 3, pieceID: null },
    { selected: false, threatID: null, type: 'light', id: 'e6', x: 2, y: 4, pieceID: null },
    { selected: false, threatID: null, type: 'dark',  id: 'f6', x: 2, y: 5, pieceID: null },
    { selected: false, threatID: null, type: 'light', id: 'g6', x: 2, y: 6, pieceID: null },
    { selected: false, threatID: null, type: 'dark',  id: 'h6', x: 2, y: 7, pieceID: null },
  ],
  [
    { selected: false, threatID: null, type: 'dark',  id: 'a5', x: 3, y: 0, pieceID: null },
    { selected: false, threatID: null, type: 'light', id: 'b5', x: 3, y: 1, pieceID: null },
    { selected: false, threatID: null, type: 'dark',  id: 'c5', x: 3, y: 2, pieceID: null },
    { selected: false, threatID: null, type: 'light', id: 'd5', x: 3, y: 3, pieceID: null },
    { selected: false, threatID: null, type: 'dark',  id: 'e5', x: 3, y: 4, pieceID: null },
    { selected: false, threatID: null, type: 'light', id: 'f5', x: 3, y: 5, pieceID: null },
    { selected: false, threatID: null, type: 'dark',  id: 'g5', x: 3, y: 6, pieceID: null },
    { selected: false, threatID: null, type: 'light', id: 'h5', x: 3, y: 7, pieceID: null },
  ],
  [
    { selected: false, threatID: null, type: 'light', id: 'a4', x: 4, y: 0, pieceID: null },
    { selected: false, threatID: null, type: 'dark',  id: 'b4', x: 4, y: 1, pieceID: null },
    { selected: false, threatID: null, type: 'light', id: 'c4', x: 4, y: 2, pieceID: null },
    { selected: false, threatID: null, type: 'dark',  id: 'd4', x: 4, y: 3, pieceID: null },
    { selected: false, threatID: null, type: 'light', id: 'e4', x: 4, y: 4, pieceID: null },
    { selected: false, threatID: null, type: 'dark',  id: 'f4', x: 4, y: 5, pieceID: null },
    { selected: false, threatID: null, type: 'light', id: 'g4', x: 4, y: 6, pieceID: null },
    { selected: false, threatID: null, type: 'dark',  id: 'h4', x: 4, y: 7, pieceID: null },
  ],
  [
    { selected: false, threatID: null, type: 'dark',  id: 'a3', x: 5, y: 0, pieceID: null },
    { selected: false, threatID: null, type: 'light', id: 'b3', x: 5, y: 1, pieceID: null },
    { selected: false, threatID: null, type: 'dark',  id: 'c3', x: 5, y: 2, pieceID: null },
    { selected: false, threatID: null, type: 'light', id: 'd3', x: 5, y: 3, pieceID: null },
    { selected: false, threatID: null, type: 'dark',  id: 'e3', x: 5, y: 4, pieceID: null },
    { selected: false, threatID: null, type: 'light', id: 'f3', x: 5, y: 5, pieceID: null },
    { selected: false, threatID: null, type: 'dark',  id: 'g3', x: 5, y: 6, pieceID: null },
    { selected: false, threatID: null, type: 'light', id: 'h3', x: 5, y: 7, pieceID: null },
  ],
  [
    { selected: false, threatID: null, type: 'light', id: 'a2', x: 6, y: 0, pieceID: 'pl1' },
    { selected: false, threatID: null, type: 'dark',  id: 'b2', x: 6, y: 1, pieceID: 'pl2' },
    { selected: false, threatID: null, type: 'light', id: 'c2', x: 6, y: 2, pieceID: 'pl3' },
    { selected: false, threatID: null, type: 'dark',  id: 'd2', x: 6, y: 3, pieceID: 'pl4' },
    { selected: false, threatID: null, type: 'light', id: 'e2', x: 6, y: 4, pieceID: 'pl5' },
    { selected: false, threatID: null, type: 'dark',  id: 'f2', x: 6, y: 5, pieceID: 'pl6' },
    { selected: false, threatID: null, type: 'light', id: 'g2', x: 6, y: 6, pieceID: 'pl7' },
    { selected: false, threatID: null, type: 'dark',  id: 'h2', x: 6, y: 7, pieceID: 'pl8' },
  ],
  [
    { selected: false, threatID: null, type: 'dark',  id: 'a1', x: 7, y: 0, pieceID: 'rl1' },
    { selected: false, threatID: null, type: 'light', id: 'b1', x: 7, y: 1, pieceID: 'nl1' },
    { selected: false, threatID: null, type: 'dark',  id: 'c1', x: 7, y: 2, pieceID: 'bl1' },
    { selected: false, threatID: null, type: 'light', id: 'd1', x: 7, y: 3, pieceID: 'ql' },
    { selected: false, threatID: null, type: 'dark',  id: 'e1', x: 7, y: 4, pieceID: 'kl' },
    { selected: false, threatID: null, type: 'light', id: 'f1', x: 7, y: 5, pieceID: 'bl2' },
    { selected: false, threatID: null, type: 'dark',  id: 'g1', x: 7, y: 6, pieceID: 'nl2' },
    { selected: false, threatID: null, type: 'light', id: 'h1', x: 7, y: 7, pieceID: 'rl2' },
  ],
]
